name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 确保这是你的主分支名

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload
        uses: withastro/action@v3
        # 如果你的代码不在根目录，可以在这里配置 path
